version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    env_file:
      - .env
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d:ro
    ports:
      - "3306:3306"
